compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: false

enableInlineHunks: false

enableScripts: false

enableStrictSsl: false

enableTelemetry: false

enableTransparentWorkspaces: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

unsafeHttpWhitelist:
  - localhost
  - 127.0.0.1
